---
name: Codespell

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@master
        with:
          skip: ./attachments
          skip: ./ws
          skip: ./opensc-projects.org
          ignore_words_file: .github/codespell_ignore_words.txt
